### PR TITLE
Routing with no locale prefixes

### PR DESCRIPTION
**Pull request by ghost**
I am facing the problem where I want to translate my routes but I do not want to have a prefix at the start of my urls, I want my locale to depend on different parameters. Since i18n_routes stopped working with 3.1 I think a cleaner approach would be using your fork.

Its a quite naive patch which do not take in consideration that locale is set random if you have the no_prefixes option set to true.

### CODE REVIEW

**Comment by francesc** [comment]
Hi Johan,

Looks good to use language by domain or subdomain. Thanks for the contribution I'll check it out and merge when have some time.

I would also appreciate if you can write down some notes on how you use it (url structure, lang detection ...) to add it to the current documentation, if you don't have time don't worry I'll write it myself.

**Comment by popdevelop** [comment]
Hi Francesc,

Thanks for the fast answer. Let me know if there are any problems with the patch. Here are some text to the documentation.

<b>No prefixes</b>

Sometimes you want to keep your url clean and set your locale from an other source such as domain or subdomain. Using the option no_prefixes generates the following structure:

  /
  /products/
  /productos/
  /contact/
  /contactos/

You can specify the following option:

  ActionDispatch::Routing::Translator.translate_from_file('config/locales/routes.yml', { :no_prefixes => true })

Note that the no_prefixes option will override the prefix_on_default_locale option.

**Comment by francesc** [comment]
Already merged and released a new version. Doc is also updated and your're listed as contributor. Thanks!

**Comment by popdevelop** [comment]
Thanks!

**Pull request merged**
