### PR TITLE
allow dashes in url segments + no more url segment downcasing

### PR DESCRIPTION
**Pull request by cawel**
Let me know what you think of my changes.

Martin

### CODE REVIEW

**Comment by francesc** [comment]
Hi Martin,

Just had a quick look over it, what's the purpose? I mean, currently you can already have dashes in a translated url, for example:

model: PressRelease
controllers: press_releases
in routes.rb: resources :press_releases
and in routes.yml: press_releases: "press-releases" in english or press_releases: "notas-de-prensa" in spanish

Is that what you tried to achieve? Correct me if I missunderstood it.

**Comment by cawel** [comment]
The issue I was trying to fix is when you have dashes in the url's with the default locale. For example, if you have a hardcoded route like this one in your "routes.rb":

```
get 'who-we-are', :to => 'staticPages#who_we_are'
```

Then your translatable_segment matcher will fail to recognize "who-we-are" as a valid url segment. Specifically, it will wrongly pick "who" as a segment (and not "who-we-are"). As a result, the route "who-we-are" will not be translated.

Let me know your thoughts.

**Comment by francesc** [comment]
Ok, I see, I'll make some tests of your branch and merge it to the repo as it doesn't break anything and adds some more flexibility for cases like the one you mention. I don't see any reason to not include it. I'll do it probably tomorrow evening. Thanks!

**Comment by cawel** [comment]
Glad I could help. Thanks!

**Comment by francesc** [comment]
Already merged your patches, all but the gem version one, I'll make some more commits and update it myself later in a new release ;)

**Comment by francesc** [comment]
Just released a new version. Doc is also updated and your're listed as contributor. Thanks!

**Pull request closed without merging**
